name = "PkgFetcher"
uuid = "6b1d9ada-aa6b-4ade-aa69-0c663c259379"
authors = ["Stefan Karpinski <stefan@karpinski.org> and contributors"]
version = "0.1.0"

[deps]
BSDiff = "7b188ff4-8bb6-4dee-bbe1-9b6fdde2c7c5"
Downloader = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
